### ISSUE TITLE
Como testar?

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/brasil-josm-preset#1]
Basicamente eu gostaria de testar o código sendo desenvolvido com Git.

**Comment by Skippern** [comment]
Não sei como melhor testar, eu carregando esse preset do local no meu computador. Outro jeito que conheço e adicionar o https://github.com/OSMBrasil/brasil-josm-preset/raw/master/Brazil-preset.xml ou https://github.com/OSMBrasil/brasil-josm-preset/archive/master.zip no menu dos presets nos configurações

**Comment by Skippern** [comment]
Olha aqui: https://josm.openstreetmap.de/wiki/Help/Preferences/Map#TaggingPresets

**Comment by alexandre-mbm** [comment]
> Olha aqui: https://josm.openstreetmap.de/wiki/Help/Preferences/Map#TaggingPresets

Conheço.

> Não sei como melhor testar, eu carregando esse preset do local no meu computador.

Mas e isso de carregar localmente, como faz?
Eu estou particularmente interessado em ter também carregadas as traduções.

**Comment by Skippern** [comment]
Eu usando do meu arquivo local para pode verificar mudanças antes fazer push.
